### ISSUE TITLE
img gpu downloading failed

### ISSUE THREAD

**Issue by COthello** [starfive-tech/VisionFive2#93]
Hi，

Seems img gpu download failed，there is no such file：http://sources.buildroot.net/img-gpu-powervr/img-gpu-powervr-bin-1.19.6345021.tar.gz'。

![image](https://github.com/starfive-tech/VisionFive2/assets/9839536/061b3af2-c65d-434a-9272-68470f4d15dd)

**Comment by mdkdir** [comment]
You have added some extra characters to the end of the link, but yes, there is no resource at http://sources.buildroot.net/img-gpu-powervr/img-gpu-powervr-bin-1.19.6345021.tar.gz

**Comment by mdkdir** [comment]
The only thing I could find relating to imagination was an empty [powervr directory.](https://sources.buildroot.net/powervr/)

**Comment by apnavik** [comment]
Yes, I am also facing similar issue. let us know where can we download the tar.


Keeping error log here:
ERROR: img-gpu-powervr-bin-1.19.6345021.tar.gz has wrong sha256 hash:
ERROR: expected: 9dcaf2084b13e59c4e50a4a288f5de56f8e9ee631627a3e818591675bf61311a
ERROR: got : 3e654c827e117e4b0e8ddba8f9d477241087e4cee2f7db307e7fb8da7d9d2259
ERROR: Incomplete download, or man-in-the-middle (MITM) attack
wget --passive-ftp -nd -t 3 -O '/home/ankit/vision_five2/VisionFive2/work/buildroot_initramfs/build/.img-gpu-powervr-bin-1.19.6345021.tar.gz.n4VV7k/output' 'http://sources.buildroot.net/img-gpu-powervr/img-gpu-powervr-bin-1.19.6345021.tar.gz'
--2024-04-16 14:45:15-- http://sources.buildroot.net/img-gpu-powervr/img-gpu-powervr-bin-1.19.6345021.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.0.37, 104.26.1.37, 172.67.72.56, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.26.0.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-04-16 14:45:15 ERROR 404: Not Found.

wget --passive-ftp -nd -t 3 -O '/home/ankit/vision_five2/VisionFive2/work/buildroot_initramfs/build/.img-gpu-powervr-bin-1.19.6345021.tar.gz.TEmbOb/output' 'http://sources.buildroot.net/img-gpu-powervr-bin-1.19.6345021.tar.gz'
--2024-04-16 14:45:15-- http://sources.buildroot.net/img-gpu-powervr-bin-1.19.6345021.tar.gz
Resolving sources.buildroot.net (sources.buildroot.net)... 104.26.1.37, 104.26.0.37, 172.67.72.56, ...
Connecting to sources.buildroot.net (sources.buildroot.net)|104.26.1.37|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2024-04-16 14:45:16 ERROR 404: Not Found.

**Comment by apnavik** [comment]
the issue is resolved with installing git-lfs and executing following commands:
`sudo apt-get install git-lfs`
`git fetch --all`
`git reset --hard origin/JH7110_VisionFive2_devel`
`rm -rf soft_3rdpart`
`git submodule update --init soft_3rdpart/`

**Comment by apnavik** [comment]
> Hi，
> 
> Seems img gpu download failed，there is no such file：[http://sources.buildroot.net/img-gpu-powervr/img-gpu-powervr-bin-1.19.6345021.tar.gz'。](http://sources.buildroot.net/img-gpu-powervr/img-gpu-powervr-bin-1.19.6345021.tar.gz'%E3%80%82)
> 
> ![image](https://private-user-images.githubusercontent.com/9839536/316208913-061b3af2-c65d-434a-9272-68470f4d15dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjQ1ODksIm5iZiI6MTcxMzI2NDI4OSwicGF0aCI6Ii85ODM5NTM2LzMxNjIwODkxMy0wNjFiM2FmMi1jNjVkLTQzNGEtOTI3Mi02ODQ3MGY0ZDE1ZGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTZUMTA0NDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTNhMDEzOTA4NzNiYmY4YTcyMDlkMTdiMjZjMjgwOWVmMjU5YzIyNjI1YmNmNGQzODcxZWE1YzE2ODAyYjU0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CehCCWBcr2S80oKqGXudG255m2Lg6UeIXtdhC5qAod8)

you can see that README file is modified with git-lfs.
https://github.com/starfive-tech/VisionFive2/blob/JH7110_VisionFive2_devel/README.md

Hope it will help!

**Comment by inhwa** [comment]
Hi 
The files in the IMG_GPU/out/ folder is still not available to download.
The git-lfs package already has been installed on my Ubuntu machine because I am using git-lfs with other projects.

After doing git fetch, git reset and rm -rf soft_3rdpart folder, I did "git submodule update --init soft_3rdpart/", but it won't.
My fail log  will be followed.. 

![image](https://github.com/user-attachments/assets/ab861b85-73a7-4d81-9b6e-fccbff26f0bf)

ihchoi@ihchoi-x1:~/ksim/riscv/VisionFive2$ git submodule update --init soft_3rdpart/
Downloading IMG_GPU/out/img-gpu-powervr-bin-1.15.6052913.tar.gz (60 MB)
Error downloading object: IMG_GPU/out/img-gpu-powervr-bin-1.15.6052913.tar.gz (66dabdd): Smudge error: Error downloading IMG_GPU/out/img-gpu-powervr-bin-1.15.6052913.tar.gz (66dabdd5964833822ba1f48c92cc7fa1be0a6f07ac63d88f560d10ba4c56684a): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

Errors logged to '/home/ihchoi/ksim/riscv/VisionFive2/.git/modules/soft_3rdpart/lfs/logs/20240926T035241.826655304.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: IMG_GPU/out/img-gpu-powervr-bin-1.15.6052913.tar.gz: smudge filter lfs failed
fatal: Unable to checkout 'c43d4fab94b0ef3b492a6382e2282fa7a2695b9b' in submodule path 'soft_3rdpart'
ihchoi@ihchoi-x1:~/ksim/riscv/VisionFive2$

**Comment by cordlandwehr** [comment]
hi @andyhu-stf , I hope to ping you directly as you are the last committer to soft_3rdpart. It seems that a quota limit for the git LFS repo is being hit. I see the same issue as reported in the last post to this issue (even though the issue at whole started as a different topic:

```
ERROR: visionfive2-pvr-graphics-1.19-r0 do_fetch: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; export PATH="/builds/packaging/yocto-meta-kf6/build-visionfive2/tmp/sysroots-uninative/x86_64-linux/usr/bin:/builds/packaging/yocto-meta-kf6/sources/poky/scripts:/builds/packaging/yocto-meta-kf6/build-visionfive2/tmp/work/riscv64-poky-linux/visionfive2-pvr-graphics/1.19/recipe-sysroot-native/usr/bin/riscv64-poky-linux:/builds/packaging/yocto-meta-kf6/build-visionfive2/tmp/work/riscv64-poky-linux/visionfive2-pvr-graphics/1.19/recipe-sysroot/usr/bin/crossscripts:/builds/packaging/yocto-meta-kf6/build-visionfive2/tmp/work/riscv64-poky-linux/visionfive2-pvr-graphics/1.19/recipe-sysroot-native/usr/sbin:/builds/packaging/yocto-meta-kf6/build-visionfive2/tmp/work/riscv64-poky-linux/visionfive2-pvr-graphics/1.19/recipe-sysroot-native/usr/bin:/builds/packaging/yocto-meta-kf6/build-visionfive2/tmp/work/riscv64-poky-linux/visionfive2-pvr-graphics/1.19/recipe-sysroot-native/sbin:/builds/packaging/yocto-meta-kf6/build-visionfive2/tmp/work/riscv64-poky-linux/visionfive2-pvr-graphics/1.19/recipe-sysroot-native/bin:/builds/packaging/yocto-meta-kf6/sources/poky/bitbake/bin:/builds/packaging/yocto-meta-kf6/build-visionfive2/tmp/hosttools"; export HOME="/home/yoctouser"; git -c gc.autoDetach=false -c core.pager=cat -c safe.bareRepository=all checkout 5eca20d2ce6fb7b18044bfe30c5bfd7f8f47958d failed with exit code 128, output:
Downloading IMG_GPU/out/img-gpu-powervr-bin-1.15.6052913.tar.gz (60 MB)
Error downloading object: IMG_GPU/out/img-gpu-powervr-bin-1.15.6052913.tar.gz (66dabdd): Smudge error: Error downloading IMG_GPU/out/img-gpu-powervr-bin-1.15.6052913.tar.gz (66dabdd5964833822ba1f48c92cc7fa1be0a6f07ac63d88f560d10ba4c56684a): batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Errors logged to /builds/packaging/yocto-meta-kf6/downloads/tmp3xpy8nc0/git/.git/lfs/logs/20241006T114801.057355931.log
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: IMG_GPU/out/img-gpu-powervr-bin-1.15.6052913.tar.gz: smudge filter lfs failed
ERROR: visionfive2-pvr-graphics-1.19-r0 do_fetch: Bitbake Fetcher Error: FetchError('Unable to fetch URL from any source.', 'git://github.com/starfive-tech/soft_3rdpart.git;protocol=https;lfs=1;nobranch=1;rev=5eca20d2ce6fb7b18044bfe30c5bfd7f8f47958d')
```

**Comment by andyhu-stf** [comment]
Hi guys, we had purchased the GitHub LFS feature now. And the download is okay on my side. Please try it again. @cordlandwehr @inhwa @COthello @apnavik @mason1920
